[project]
name = "migration-demo"
version = "0.1.0"
description = "Automated cloud migration using GenAI and MCP servers"
dependencies = [
    "mcp>=1.0.0",
    "boto3",
    "python-dotenv",
    "pydantic",
    "langgraph>=0.0.40",
    "langchain-core",
]
requires-python = ">=3.10"
